### ISSUE TITLE
Crash while installing mod

### ISSUE THREAD

**Issue by saulrh** [Deli-Collective/DeliCounter#7]
What I did:

1. Start with clean H3VR installation
2. Open Deli Counter
3. Search for promeatheus
4. Click "install" button at bottom of mod page
5. Wait for downloads to complete
6. Deli Counter crashes

Crash occurred at the end of installation, basically at the same time the progress bar finished and turned into "4 operation(s) completed successfully!". I reopened deli counter to debug and the installation seems to have in fact been successful.

Contents of diagnostic dump, taken after I reopened deli counter:

Version:
```
== Diagnostic Info ==
Generated at: 3/7/2021 10:14:58 PM
Game Directory: E:\SteamLibrary\steamapps\common\H3VR\

== DeliCounter Git Info ==
Tag: v0.1.11
Branch: undefined (4bf4582)
Commit Date: 3/5/2021 4:52:56 PM
```

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DeliCounter.Pages.SearchPage.ModList_SelectionChanged(Object sender, SelectionChangedEventArgs e) in D:\a\DeliCounter\DeliCounter\DeliCounter\Pages\SearchPage.xaml.cs:line 26
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ListView.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at MS.Internal.Controls.InnerItemCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.RefreshOrDefer()
   at MS.Internal.Controls.InnerItemCollectionView.Clear()
   at System.Windows.Controls.ItemCollection.Clear()
   at DeliCounter.Pages.SearchPage.UpdateSearch(String query) in D:\a\DeliCounter\DeliCounter\DeliCounter\Pages\SearchPage.xaml.cs:line 38
   at DeliCounter.Pages.SearchPage.<Instance_InstalledModsUpdated>b__1_0() in D:\a\DeliCounter\DeliCounter\DeliCounter\Pages\SearchPage.xaml.cs:line 19
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DeliCounter.App.RunInMainThread(Action action) in D:\a\DeliCounter\DeliCounter\DeliCounter\App.xaml.cs:line 39
   at DeliCounter.Pages.SearchPage.Instance_InstalledModsUpdated() in D:\a\DeliCounter\DeliCounter\DeliCounter\Pages\SearchPage.xaml.cs:line 19
   at DeliCounter.Backend.ModRepository.WriteCache() in D:\a\DeliCounter\DeliCounter\DeliCounter\Backend\ModRepository.cs:line 267
   at DeliCounter.Backend.ModManagement.ExecuteOperations(IEnumerable`1 operations) in D:\a\DeliCounter\DeliCounter\DeliCounter\Backend\ModManagement.cs:line 154
   at DeliCounter.Backend.ModManagement.<>c__DisplayClass0_0.<InstallMod>b__0() in D:\a\DeliCounter\DeliCounter\DeliCounter\Backend\ModManagement.cs:line 16
   at DeliCounter.App.<>c__DisplayClass7_0.<RunInBackgroundThread>b__0(Object _) in D:\a\DeliCounter\DeliCounter\DeliCounter\App.xaml.cs:line 34
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Tree:
```
Generated at 3/7/2021 10:14:58 PM
Folder PATH listing for volume New Volume
Volume serial number is 0C71-AC62
E:\STEAMLIBRARY\STEAMAPPS\COMMON\H3VR
|   actions.json
|   bindings_holographic_controller.json
|   bindings_hp_reverb2_controller.json
|   bindings_knuckles.json
|   bindings_oculus_touch.json
|   bindings_vive_controller.json
|   bindings_vive_cosmos_controller.json
|   binding_holographic_hmd.json
|   binding_rift.json
|   binding_vive.json
|   binding_vive_pro.json
|   binding_vive_tracker_camera.json
|   changelog.txt
|   doorstop_config.ini
|   h3vr.exe
|   installed_mods.json
|   steam_api64.dll
|   winhttp.dll
|   
+---BepInEx
|   +---core
|   |       0Harmony.dll
|   |       0Harmony.xml
|   |       0Harmony20.dll
|   |       BepInEx.dll
|   |       BepInEx.Harmony.dll
|   |       BepInEx.Harmony.xml
|   |       BepInEx.Preloader.dll
|   |       BepInEx.Preloader.xml
|   |       BepInEx.xml
|   |       HarmonyXInterop.dll
|   |       Mono.Cecil.dll
|   |       Mono.Cecil.Mdb.dll
|   |       Mono.Cecil.Pdb.dll
|   |       Mono.Cecil.Rocks.dll
|   |       MonoMod.RuntimeDetour.dll
|   |       MonoMod.RuntimeDetour.xml
|   |       MonoMod.Utils.dll
|   |       MonoMod.Utils.xml
|   |       
|   +---patchers
|   |   \---Deli
|   |           ADepIn.dll
|   |           Deli.dll
|   |           DotNetZip.dll
|   |           I18N.dll
|   |           I18N.West.dll
|   |           
|   \---plugins
|       \---Deli
|               Deli.Runtime.dll
|               
+---h3vr_Data (TRUNCATED)
|           
\---mods
        Deli.Core.deli
        Deli.MonoMod.deli
        Promeatheus.deli
        WurstMod_2.0.2.0.deli
```

System information:
```
Processor	AMD EPYC-Rome Processor   3.80 GHz
Installed RAM	31.3 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎16/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by nrgill28** [comment]
Fixed with the release of [v0.1.12](https://github.com/Deli-Collective/DeliCounter/releases/tag/v0.1.12), thank you for the report!
Also, I super appreciate all the details right from the start, many thanks for that😁
